[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

db_host = dbCp
db_port = 5432
db_user = odoo
db_password = odoo

list_db = true
log_db = False
log_handler = :INFO,odoo.sql_db:WARNING
log_level = info
admin_passwd = odoo18


# Configuración de la base de datos
# db_host = odoo-18-dbCp-1  
# db_port = 5432            
# db_user = odoo            
# db_password = odoo      


